Internal Server Error: /
Traceback (most recent call last):
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/connection.py", line 874, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/connection.py", line 347, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/connection.py", line 357, in _read_response
    raw = self._buffer.readline()
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/connection.py", line 260, in readline
    self._read_from_socket()
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/connection.py", line 210, in _read_from_socket
    data = self._sock.recv(socket_read_size)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/kombu/connection.py", line 523, in _ensured
    return fun(*args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/kombu/messaging.py", line 199, in _publish
    return channel.basic_publish(
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 599, in basic_publish
    return self._put(routing_key, message, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/kombu/transport/redis.py", line 1012, in _put
    client.lpush(self._q_for_pri(queue, pri), dumps(message))
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/commands/core.py", line 2706, in lpush
    return self.execute_command("LPUSH", name, *values)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/client.py", line 1269, in execute_command
    return conn.retry.call_with_retry(
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/client.py", line 1273, in <lambda>
    lambda error: self._disconnect_raise(conn, error),
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/client.py", line 1259, in _disconnect_raise
    raise error
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/client.py", line 1270, in <lambda>
    lambda: self._send_command_parse_response(
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/client.py", line 1246, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/client.py", line 1286, in parse_response
    response = connection.read_response()
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/connection.py", line 882, in read_response
    raise ConnectionError(
redis.exceptions.ConnectionError: Error while reading from 127.0.0.1:6379 : (104, 'Connection reset by peer')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 925, in create_channel
    return self._avail_channels.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/kombu/connection.py", line 446, in _reraise_as_library_errors
    yield
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/kombu/connection.py", line 540, in _ensured
    self._ensure_connection(
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/kombu/connection.py", line 433, in _ensure_connection
    return retry_over_time(
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/kombu/utils/functional.py", line 312, in retry_over_time
    return fun(*args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/kombu/connection.py", line 877, in _connection_factory
    self._connection = self._establish_connection()
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/kombu/connection.py", line 812, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 949, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 927, in create_channel
    channel = self.Channel(connection)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/kombu/transport/redis.py", line 737, in __init__
    self.client.ping()
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/commands/core.py", line 1205, in ping
    return self.execute_command("PING", **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/connection.py", line 1457, in get_connection
    connection.connect()
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/views.py", line 29, in get_queryset
    update_book_data.delay(book.id)  # Передача идентификатора объекта в таску
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/celery/app/task.py", line 425, in delay
    return self.apply_async(args, kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/celery/app/task.py", line 575, in apply_async
    return app.send_task(
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/celery/app/base.py", line 788, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/celery/app/amqp.py", line 510, in send_task_message
    ret = producer.publish(
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/kombu/messaging.py", line 177, in publish
    return _publish(
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/kombu/connection.py", line 520, in _ensured
    with self._reraise_as_library_errors():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/kombu/connection.py", line 450, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
/home/egor/Рабочий стол/MyProjects/IT_proj/IT_project/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/api.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /new_book/
Traceback (most recent call last):
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 135, in form_valid
    self.object = form.save()
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py", line 47, in save
    book.image.save(f'{title}.jpg', ContentFile(book_data['image_data']), save=True)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/files/base.py", line 129, in __init__
    self.size = len(content)
TypeError: object of type 'NoneType' has no len()
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/api.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/api.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/api.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/api.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/IT_project/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/IT_project/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/views.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/api.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/views.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /edit_book/53/
Traceback (most recent call last):
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 208, in post
    return super().post(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 135, in form_valid
    self.object = form.save()
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py", line 80, in save
    if book_data['author'] != self.author:
AttributeError: 'EditBookForm' object has no attribute 'author'
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /edit_book/53/
Traceback (most recent call last):
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 208, in post
    return super().post(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 135, in form_valid
    self.object = form.save()
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py", line 80, in save
    if book_data['author'] != self.author:
AttributeError: 'EditBookForm' object has no attribute 'author'
Internal Server Error: /edit_book/53/
Traceback (most recent call last):
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 208, in post
    return super().post(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 135, in form_valid
    self.object = form.save()
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py", line 80, in save
    if book_data['author'] != self.author:
AttributeError: 'EditBookForm' object has no attribute 'author'
Internal Server Error: /edit_book/53/
Traceback (most recent call last):
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 208, in post
    return super().post(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 135, in form_valid
    self.object = form.save()
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py", line 80, in save
    if book_data['author'] != self.author:
AttributeError: 'EditBookForm' object has no attribute 'author'
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /edit_book/53/
Traceback (most recent call last):
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 208, in post
    return super().post(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 135, in form_valid
    self.object = form.save()
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py", line 78, in save
    update_book_data(self.id)
AttributeError: 'EditBookForm' object has no attribute 'id'
Internal Server Error: /edit_book/53/
Traceback (most recent call last):
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 208, in post
    return super().post(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 135, in form_valid
    self.object = form.save()
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py", line 78, in save
    update_book_data(self.id)
AttributeError: 'EditBookForm' object has no attribute 'id'
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/IT_project/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/IT_project/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/IT_project/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/IT_project/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/IT_project/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/IT_project/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/IT_project/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /edit_book/56/
Traceback (most recent call last):
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 208, in post
    return super().post(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 136, in form_valid
    return super().form_valid(form)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 122, in get_success_url
    url = self.success_url.format(**self.object.__dict__)
AttributeError: 'NoneType' object has no attribute '__dict__'
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /edit_book/56/
Traceback (most recent call last):
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 208, in post
    return super().post(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 136, in form_valid
    return super().form_valid(form)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 122, in get_success_url
    url = self.success_url.format(**self.object.__dict__)
AttributeError: 'NoneType' object has no attribute '__dict__'
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /edit_book/56/
Traceback (most recent call last):
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 208, in post
    return super().post(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 136, in form_valid
    return super().form_valid(form)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 122, in get_success_url
    url = self.success_url.format(**self.object.__dict__)
AttributeError: 'NoneType' object has no attribute '__dict__'
Internal Server Error: /edit_book/56/
Traceback (most recent call last):
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 208, in post
    return super().post(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 136, in form_valid
    return super().form_valid(form)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 122, in get_success_url
    url = self.success_url.format(**self.object.__dict__)
AttributeError: 'NoneType' object has no attribute '__dict__'
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /edit_book/57/
Traceback (most recent call last):
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 208, in post
    return super().post(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 136, in form_valid
    return super().form_valid(form)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 122, in get_success_url
    url = self.success_url.format(**self.object.__dict__)
AttributeError: 'NoneType' object has no attribute '__dict__'
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Not Found: /media/products_img/451_по_Фаренгейту_7iTROYy.jpg
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/views.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /23/delete/
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Internal Server Error: /new_book/
Traceback (most recent call last):
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fa6104b2e90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: /books/v1/volumes?q=intitle%3Afyukfyukf&maxResults=5&key=AIzaSyDJx2F1tfeCsMYgCaOP2fXBV8ne1dfbYP0 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa6104b2e90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 152, in post
    if form.is_valid():
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/forms/forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/forms/forms.py", line 434, in full_clean
    self._clean_form()
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/django/forms/forms.py", line 455, in _clean_form
    cleaned_data = self.clean()
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py", line 24, in clean
    book_data = get_book_data(title)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/api.py", line 13, in get_book_data
    response = requests.get(url, params=params)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/egor/Рабочий стол/MyProjects/IT_proj/venv/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: /books/v1/volumes?q=intitle%3Afyukfyukf&maxResults=5&key=AIzaSyDJx2F1tfeCsMYgCaOP2fXBV8ne1dfbYP0 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa6104b2e90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Ошибка при создании книги: * __all__
  * Книга не найдена
Watching for file changes with StatReloader
Not Found: /media/products_img/Виноваты_звезды_IwujRRb.jpg
Not Found: /media/products_img/451_по_Фаренгейту_DpeHuS2.jpg
Not Found: /media/products_img/Пикник_на_обочине_QhhsfQ0.jpg
Not Found: /media/products_img/451_по_Фаренгейту_DpeHuS2.jpg
Not Found: /media/products_img/Пикник_на_обочине_QhhsfQ0.jpg
Not Found: /media/products_img/Виноваты_звезды_IwujRRb.jpg
Not Found: /media/products_img/Виноваты_звезды_IwujRRb.jpg
Not Found: /media/products_img/Пикник_на_обочине_QhhsfQ0.jpg
Not Found: /media/products_img/451_по_Фаренгейту_DpeHuS2.jpg
Not Found: /media/products_img/Пикник_на_обочине_QhhsfQ0.jpg
Not Found: /media/products_img/451_по_Фаренгейту_DpeHuS2.jpg
Not Found: /media/products_img/Виноваты_звезды_IwujRRb.jpg
Not Found: /media/products_img/451_по_Фаренгейту_DpeHuS2.jpg
Not Found: /media/products_img/Виноваты_звезды_IwujRRb.jpg
Not Found: /media/products_img/Пикник_на_обочине_QhhsfQ0.jpg
Not Found: /media/products_img/Пикник_на_обочине_QhhsfQ0.jpg
Not Found: /media/products_img/Виноваты_звезды_IwujRRb.jpg
Not Found: /media/products_img/451_по_Фаренгейту_DpeHuS2.jpg
Not Found: /media/products_img/Виноваты_звезды_IwujRRb.jpg
Not Found: /media/products_img/451_по_Фаренгейту_DpeHuS2.jpg
Not Found: /media/products_img/Пикник_на_обочине_QhhsfQ0.jpg
Not Found: /media/products_img/451_по_Фаренгейту_DpeHuS2.jpg
Not Found: /media/products_img/Пикник_на_обочине_QhhsfQ0.jpg
Not Found: /media/products_img/Виноваты_звезды_IwujRRb.jpg
Not Found: /media/products_img/Пикник_на_обочине_QhhsfQ0.jpg
Not Found: /media/products_img/Виноваты_звезды_IwujRRb.jpg
Not Found: /media/products_img/451_по_Фаренгейту_DpeHuS2.jpg
Not Found: /media/products_img/451_по_Фаренгейту_DpeHuS2.jpg
Not Found: /media/products_img/Пикник_на_обочине_QhhsfQ0.jpg
Not Found: /media/products_img/Виноваты_звезды_IwujRRb.jpg
Not Found: /media/products_img/451_по_Фаренгейту_DpeHuS2.jpg
Not Found: /media/products_img/Виноваты_звезды_IwujRRb.jpg
Not Found: /media/products_img/Пикник_на_обочине_QhhsfQ0.jpg
Not Found: /media/products_img/451_по_Фаренгейту_DpeHuS2.jpg
Not Found: /media/products_img/Пикник_на_обочине_QhhsfQ0.jpg
Not Found: /media/products_img/Виноваты_звезды_IwujRRb.jpg
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
Not Found: /media/products_img/Пикник_на_обочине_LEMp9Fn.jpg
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
Not Found: /media/products_img/Виноваты_звезды_buF5yoH.jpg
/home/egor/Рабочий стол/MyProjects/IT_proj/IT_project/settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /media/products_img/451_по_Фаренгейту_xGuzglQ.jpg
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
Not Found: /media/products_img/Пикник_на_обочине_Bkbx8EP.jpg
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/tasks.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/views.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/book_shop/forms.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/IT_project/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/egor/Рабочий стол/MyProjects/IT_proj/manage.py changed, reloading.
